// <auto-generated />
using System;
using DesafioNet.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioNet.Data.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20230505014119_PrimeiraMigracao")]
    partial class PrimeiraMigracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DesafioNet.Business.Models.Chave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TipoChave")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chave");
                });

            modelBuilder.Entity("DesafioNet.Business.Models.Pagador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChaveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveId");

                    b.ToTable("Pagador");
                });

            modelBuilder.Entity("DesafioNet.Business.Models.Recebedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChaveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveId");

                    b.ToTable("Recebedor");
                });

            modelBuilder.Entity("DesafioNet.Business.Models.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("date");

                    b.Property<int>("PagadorId")
                        .HasColumnType("int");

                    b.Property<Guid>("PagadorId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RecebedorId")
                        .HasColumnType("int");

                    b.Property<Guid>("RecebedorId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PagadorId1");

                    b.HasIndex("RecebedorId1");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("DesafioNet.Business.Models.Pagador", b =>
                {
                    b.HasOne("DesafioNet.Business.Models.Chave", "Chave")
                        .WithMany()
                        .HasForeignKey("ChaveId");

                    b.Navigation("Chave");
                });

            modelBuilder.Entity("DesafioNet.Business.Models.Recebedor", b =>
                {
                    b.HasOne("DesafioNet.Business.Models.Chave", "Chave")
                        .WithMany()
                        .HasForeignKey("ChaveId");

                    b.Navigation("Chave");
                });

            modelBuilder.Entity("DesafioNet.Business.Models.Transacao", b =>
                {
                    b.HasOne("DesafioNet.Business.Models.Pagador", "Pagador")
                        .WithMany("Transacoes")
                        .HasForeignKey("PagadorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesafioNet.Business.Models.Recebedor", "Recebedor")
                        .WithMany("Transacoes")
                        .HasForeignKey("RecebedorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pagador");

                    b.Navigation("Recebedor");
                });

            modelBuilder.Entity("DesafioNet.Business.Models.Pagador", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("DesafioNet.Business.Models.Recebedor", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
